server:
  port: 8001

spring:
  application:
    name: config

    # 单数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/electricity_mall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


mybatis-plus:
  type-enums-package: com.indi.electricity.mall.model.**.enums.StateEnum
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
